# config/app.yml for rails-settings-cached
defaults: &defaults
  headers:
    付款账户: #付款账户
      - '交易卡号'
      - '对方'
      - '对方账号'
      - '流水号'
      - '对方账户账号'
      - '对方账户'
      - '对手方账号'
      - '收/付方帐号'
    回款客户: #回款客户
      - '对方户名/商户名'
      - '对方名称'
      - '对方账户名称'
      - '对方账号名称'
      - '对方行名称'
      - '对方姓名'
      - '对方户名'
      - '对手方户名'
      - '外行账户名称'
      - '收/付方名称'
    回款金额: #回款金额
      - '收入金额'
      - '交易金额'
      - '存入金额'
      - '贷方发生额'
      - '收入'
      - '贷'
      - '贷方金额'
      - '金额'
      - '贷方发生额（收入）'
      - '转入'
    回款日期: #回款时间
      - '交易日期'
      - '交易日'
    备注: #备注
      - '备注'
    回款时间:
      - '交易时间'
    摘要: #备注
      - '摘要'
    是否充值款: #是否充值款
  filters:
    - '收入金额'
    - '交易金额'
    - '存入金额'
    - '贷方发生额'
    - '收入'
    - '贷'
    - '贷方金额'
    - '金额'
    - '贷方发生额（收入）'
    - '转入'
#    - '支出金额'
#    - '交易描述'
#    - '转出'
#    - '支出'
#    - '借方发生额'
#    - '借'
#    - '借方金额'
#    - '借方发生额（支取）'
#    - '交易标志'
#    - '摘要'
#    - '往来账'
#    - '收支状况'
#    - '交易类型'
#    - '借贷标志'
  filter_values:
    - '支出'
    - '借'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
